from __future__ import annotations

import os
import re
from pathlib import Path

from sqlalchemy import create_engine, event
from sqlalchemy.orm import declarative_base, sessionmaker


APP_DIR = Path(__file__).resolve().parent
DATA_DIR = APP_DIR / "data"
DATA_DIR.mkdir(parents=True, exist_ok=True)
DB_PATH = DATA_DIR / "godeyes.db"

# Render will provide DATABASE_URL for the persistent PostgreSQL database.
# SQLite remains available as a local-development fallback.
raw_database_url = str(os.environ.get("DATABASE_URL", "")).strip()
if raw_database_url:
    if raw_database_url.startswith("postgres://"):
        raw_database_url = "postgresql+psycopg://" + raw_database_url[len("postgres://"):]
    elif raw_database_url.startswith("postgresql://"):
        raw_database_url = "postgresql+psycopg://" + raw_database_url[len("postgresql://"):]
    DATABASE_URL = raw_database_url
else:
    DATABASE_URL = f"sqlite:///{DB_PATH.as_posix()}"

is_postgres = DATABASE_URL.startswith("postgresql+") or DATABASE_URL.startswith("postgresql://")
is_sqlite = DATABASE_URL.startswith("sqlite://")

engine_kwargs = {
    "future": True,
    "pool_pre_ping": True,
}
if is_sqlite:
    engine_kwargs["connect_args"] = {"check_same_thread": False}

engine = create_engine(DATABASE_URL, **engine_kwargs)


@event.listens_for(engine, "before_cursor_execute", retval=True)
def _portable_sql(conn, cursor, statement, parameters, context, executemany):
    """Keep the existing SQLite-oriented raw SQL compatible with PostgreSQL."""
    if conn.dialect.name == "postgresql":
        # SQLite AUTOINCREMENT -> PostgreSQL identity column.
        statement = re.sub(
            r"INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT",
            "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            statement,
            flags=re.IGNORECASE,
        )
        # Existing timestamp fields are TEXT, so cast the PostgreSQL timestamp.
        statement = re.sub(
            r"DEFAULT\s+CURRENT_TIMESTAMP\b",
            "DEFAULT (CURRENT_TIMESTAMP::text)",
            statement,
            flags=re.IGNORECASE,
        )
    return statement, parameters


SessionLocal = sessionmaker(
    bind=engine,
    autocommit=False,
    autoflush=False,
    future=True,
)

# Kept for compatibility with modules that may import Base from database.py.
Base = declarative_base()
